swagger: '2.0'
schemes:
  - https
host: yosgo-api-policer.herokuapp.com
basePath: /_api/v1
info:
  description: |

    # 簡介
    有鑒於一貫的廣告策略費用不斷升高，YOSGO 致力提供各種行銷工具模組，透過SaaS服務的方式整合至您的產品服務中，讓銷售就是行銷！

    上線服務
    * LINA 揪團模組
  version: 1.0.0
  title: YOSGO Docs
  termsOfService: ''
  contact:
    email: support@yosgo.com
    url: 'https:yosgo.com'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://s3-ap-northeast-1.amazonaws.com/yosgo-images/yosgo-vertical.png'
externalDocs:
  description: 註冊取得YOSGO API KEY
  url: 'https://dashboard.yosgo.com/signup'
produces:
  - application/json
  - application/xml
  - text/csv
consumes:
  - application/json
  - application/xml
tags:
  - name: LINA
    description: |
      LINA 是一套整合揪團流程與第三方支付的 API 接口，透過 LINA 你可以快速打造揪團應用程式。

      整體 API 架構如下
      1. 品牌：可以做為事業體的分類，每個品牌底下會有數個產品
      2. 產品：即為揪團銷售的產品，產品屬於某個品牌，每個產品建立時需設定該產品的揪團規則
      3. 揪團：揪團產生時將會套用所屬產品的揪團規則
      4. 訂單：從揪團中產生訂單，若訂單狀態為已付款，其購買數量就會被算入揪團成團的進度
      5. 購買人資料：建立訂單時需要帶入訂購人資料，一筆訂單視應用情境可以填入至少一筆或多筆購買人資料。

      金流基礎，目前提供 Ecpay 的線上刷卡，台灣的智付通正在籌備開通中。透過 YOSOGO 管理後台，將你的HaskKey, IV, ID 即可設定 LINA API 的金流接口至你的帳戶中。

      更進一步
      1. 串接 LINA 需要有 YOSGO-API-KEY，請先至此 **[註冊](https://dashboard.yosgo.com/signup)**，目前僅限公司單位註冊
      2. 若你是第一次開發揪團應用或是想更進一步了解開發上的細節，請參考 **[LINA 應用程式開發指南]()**
securityDefinitions:
  main_auth:
    type: oauth2
    authorizationUrl: 'http://example.com/api/oauth/dialog'
    flow: implicit
    scopes:
      'read:users': read users info
      'write:users': modify or remove users
  api_key:
    type: apiKey
    in: header
    name: yosgo-api-key
  basic_auth:
    type: basic
paths:
  /brands:
    post:
      tags:
        - LINA
      summary: 建立品牌
      description: 相關描述待補充
      parameters:
        - name: title
          in: body
          required: true
          description: 建立的品牌名稱
          schema:
            type: object
            properties:
              title:
                type: string
                description: 一段描述
      security:
        - api_key: []
      responses:
        '200':
          description: 成功建立品牌
          schema:
            $ref: '#/definitions/PostSuccessResponse'
    get:
      tags:
        - LINA
      summary: 所有品牌
      description: 查詢帳戶中的所有品牌，回傳帳戶中的所有品牌資料
      responses:
        '200':
          description: 成功
          schema:
            type: array
            items:
              type: object
              properties:
                objectId:
                  type: string
                  description: 品牌的Id
                title:
                  type: string
                  description: 品牌名稱
                createdAt:
                  type: string
                  description: 建立時間
  /products:
    post:
      tags:
        - LINA
      summary: 建立產品
      description: 一段描述
      parameters:
        - name: body
          in: body
          required: true
          description: 建立產品所需資料，包含揪團規則設定
          schema:
            type: object
            properties:
              brandId:
                type: string
                description: 產品所屬品牌Id
                example: kcjSIyGSkK
              title:
                type: string
                description: 產品的名稱
              description:
                type: string
                description: 產品的簡述
              photo:
                type: string
                description: 產品圖片網址，非必填
              minQuantity:
                type: number
                description: 揪團此產品，最低成團數量
              maxQuantity:
                type: number
                description: 揪團此產品，最高購買數量上限，僅為參考值
              unitPrice:
                type: number
                description: 產品價格
              groupDayLength:
                type: number
                description: 揪團天數
              endDateTime:
                type: object
                description: 產品販售截止時間
                properties:
                  __type:
                    type: string
                    description: 日期固定格式，請輸入字串 Date
                    example: Date
                  iso:
                    type: string
                    description: 請將日期轉換為 iso 格式
              isActive:
                type: boolean
                description: 請帶'true'
                example: 'true'
      security:
        - api_key: []
      responses:
        '200':
          description: 成功建立產品
          schema:
            $ref: '#/definitions/PostSuccessResponse'
    get:
      tags:
        - LINA
      summary: 所有產品
      description: 查詢帳戶中的所有品牌，回傳帳戶中的所有產品資料
      responses:
        '200':
          description: 成功
          schema:
            type: array
            items:
              type: object
              properties:
                brandId:
                  type: string
                  description: 產品所屬品牌Id
                title:
                  type: string
                  description: 產品的名稱
                description:
                  type: string
                  description: 產品的簡述
                minQuantity:
                  type: number
                  description: 最低成團數量
                maxQuantity:
                  type: number
                  description: 最高購買數量上限
                unitPrice:
                  type: number
                  description: 產品價格
                groupDayLength:
                  type: number
                  description: 揪團天數
                endDateTime:
                  type: object
                  description: 產品販售截止時間
                  properties:
                    __type:
                      type: string
                      description: 日期固定格式
                      example: Date
                    iso:
                      type: string
                      description: 請將日期轉換為 iso 格式
                isActive:
                  type: boolean
                  description: 產品是否在銷售中
  '/products/{productId}':
    get:
      tags:
        - LINA
      summary: 特定產品
      description: |
        查詢特定產品的資料，將會返回該產品下方所包含的揪團、揪團內的訂單以及每筆訂單的購買人資料。將會進行伺服器快取 15 分鐘。可以網址後方加上 `?forceUpdate=1` 來取得最新資料。
      parameters:
        - name: productId
          in: path
          description: 某個產品的id
          required: true
          type: string
      responses:
        '200':
          description: 成功
          schema:
            type: object
            properties:
              brandId:
                type: string
                description: 產品所屬品牌Id
              title:
                type: string
                description: 產品的名稱
              description:
                type: string
                description: 產品的簡述
              minQuantity:
                type: number
                description: 最低成團數量
              maxQuantity:
                type: number
                description: 最高購買數量上限
              unitPrice:
                type: number
                description: 產品價格
              groupDayLength:
                type: number
                description: 揪團天數
              endDateTime:
                type: object
                description: 產品販售截止時間
                properties:
                  __type:
                    type: string
                    description: 日期固定格式
                    example: Date
                  iso:
                    type: string
                    description: 請將日期轉換為 iso 格式
              isActive:
                type: boolean
                description: 產品是否在銷售中
  /groups:
    post:
      tags:
        - LINA
      summary: 建立揪團
      description: 一段描述
      parameters:
        - name: body
          in: body
          required: true
          description: 建立揪團所需資料
          schema:
            type: object
            properties:
              productId:
                type: string
                description: 產品Id
              notes:
                type: string
                description: 該揪團的備註
      security:
        - api_key: []
      responses:
        '200':
          description: 成功
          schema:
            $ref: '#/definitions/PostSuccessResponse'
  '/groups/{groupId}':
    get:
      tags:
        - LINA
      summary: 特定揪團
      description: |
        一段描述
      parameters:
        - name: groupId
          in: path
          description: 某個揪團的Id
          required: true
          type: string
      security:
        - api_key: []
      responses:
        '200':
          description: 成功
          schema:
            $ref: '#/definitions/GroupWithIdSuccessResponse'
  /orders:
    post:
      tags:
        - LINA
      summary: 產生訂單
      description: 一段描述
      parameters:
        - name: body
          in: body
          required: true
          description: 建立訂單所需資料
          schema:
            type: object
            properties:
              order:
                $ref: '#/definitions/OrderCreateType'
              registration:
                $ref: '#/definitions/RegistrationType'
              extraRegistrations:
                type: array
                items:
                  $ref: '#/definitions/ExtraRegistrationsType'
      security:
        - api_key: []
      responses:
        '200':
          description: 成功
          schema:
            $ref: '#/definitions/OrderCreateResponseType'
  /orders/payment:
    post:
      tags:
        - LINA
      summary: 訂單付款
      description: 為已建立的訂單付款，並取得綠界支付的表格
      parameters:
        - name: body
          in: body
          required: true
          description: 訂單付款所需資料
          schema:
            type: object
            properties:
              orderId:
                type: string
                description: 訂單Id
              next:
                type: string
                description: 付款後導向網址
      security:
        - api_key: []
      responses:
        '200':
          description: 成功
          schema:
            $ref: '#/definitions/PostSuccessResponse'
  /registrations:
    get:
      tags:
        - LINA
      summary: 取得購買人資料
      description: 取得一筆或是多筆註冊資料
      parameters:
        - name: registrationIds
          in: query
          description: |
            query 範例 `?registrationIds=購買人Id1, 購買人Id2, 購買人Id3`
          required: true
          type: string
      security:
        - api_key: []
      responses:
        '200':
          description: 成功
          schema:
            $ref: '#/definitions/PostSuccessResponse'
definitions:
  Email:
    description: User email address
    type: string
    format: email
    example: john.smith@example.com
  User:
    type: object
    properties:
      username:
        description: User supplied username
        type: string
        minLength: 4
        example: John78
      firstName:
        description: User first name
        type: string
        minLength: 1
        example: John
      lastName:
        description: User last name
        type: string
        minLength: 1
        example: Smith
      email:
        $ref: '#/definitions/Email'
  PostSuccessResponse:
    type: object
    properties:
      payload:
        type: object
        description: 相關資料的物件
      message:
        type: string
        description: 成功訊息說明
      status:
        type: number
        example: 200
        description: http 狀態碼
      error:
        type: string
        description: 成功呼叫 api 時，error 值為空字串
  GroupWithIdSuccessResponse:
    type: object
    properties:
      payload:
        type: object
        description: 某個揪團的資料
        properties:
          objectId:
            type: string
            description: 該揪團的id
          orders:
            type: array
            description: 訂單陣列
            items:
              type: object
              description: 每筆訂單的資訊物件
          product:
            type: object
            description: 產品資料物件
          note:
            type: string
            description: 該揪團的備註欄位
          isLocked:
            type: boolean
            description: 此揪團是否已經結束
          groupEndDateTime:
            type: object
            description: 此揪團截止時間
          createdAt:
            type: object
            description: 此揪團的建立時間
          updatedAt:
            type: object
            description: 此揪團的更新時間
      message:
        type: string
        description: 成功訊息說明
      status:
        type: number
        example: 200
        description: http 狀態碼
      error:
        type: string
        example: null
        description: 成功呼叫 api 時，error 值為空字串
  DateType:
    type: object
    properties:
      __type:
        type: string
        example: Date
        description: 請帶入 Date
      iso:
        type: string
        description: ISO的日期格式字串
        example: '2018-01-10T11:14:50.298Z'
  RegistrationType:
    type: object
    description: 購買人資料
    properties:
      name:
        type: string
        description: 購買人姓名
      phone:
        type: string
        description: 購買人手機
      email:
        type: string
        description: 購買人信箱
      notes:
        type: string
        description: 購買人備註欄，可以在此欄位存入此購買人的其他資料
      address:
        type: string
        description: 購買人地址，非必填
  ExtraRegistrationsType:
    type: array
    description: 其他購買人資料，若同一筆訂單有數個購買人資訊，請將第二位以及後續的購買人放置在此，每一位購買人的資訊均為物件，以陣列包裝
    items:
      type: object
      properties:
        name:
          type: string
          description: 其他購買人姓名
        phone:
          type: string
          description: 其他購買人手機
        email:
          type: string
          description: 其他購買人信箱
        notes:
          type: string
          description: 其他購買人備註欄，可以在此欄位存入此購買人的其他資料
        address:
          type: string
          description: 其他購買人地址，非必填
  OrderCreateType:
    type: object
    description: 訂單資訊
    properties:
      quantity:
        type: number
        description: 訂單的購買數量
      productId:
        type: string
        description: 所屬產品的Id
      groupId:
        type: string
        description: 所屬揪團的Id
  OrderCreateResponseType:
    type: object
    description: 建立訂單的回傳格式
    properties:
      payload:
        type: object
        description: 訂單相關資料
        properties:
          objectId:
            type: string
            description: 訂單id
          payment:
            type: object
            description: 訂單的付款資訊
          product:
            type: object
            description: 訂單所屬產品的資訊
          company:
            type: object
            description: 訂單所屬的公司資訊
          group:
            type: object
            description: 訂單所屬的揪團資訊
          registration:
            type: object
            description: 訂單的購買人資訊
          extraRegistration:
            type: array
            description: 其他購買人資訊陣列
            items:
              type: object
              description: 其他購買人資訊物件
          quantity:
            type: number
            description: 訂單購買數量
          isArchived:
            type: boolean
            description: 訂單是否已封存
          createdAt:
            $ref: '#/definitions/DateType'
          updatedAt:
            $ref: '#/definitions/DateType'
      message:
        type: string
        description: 成功訊息說明
      status:
        type: number
        example: 200
        description: http 狀態碼
      error:
        type: string
        description: 成功呼叫 api 時，error 值為空字串
